import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Chart, Check, Compass, Shield, Spark } from '@/components/Icons';
import { ServiceCard } from '@/components/ServiceCard';
import { SectionTitle } from '@/components/SectionTitle';
import { services, industries, insights, site } from '@/lib/site';

export default function Home(){return <main>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Better insights. Stronger processes. Sustainable growth.</span><h1>Build a business that is <span>ready for what’s next.</span></h1><p className="hero-lead">{site.name} provides practical, tailored support for businesses that want clearer processes, stronger controls, healthier cash flow and confident decision-making.</p><div className="hero-actions"><Link className="button button-primary" href="/contact">Book a Consultation <ArrowRight/></Link><Link className="button button-secondary" href="/services">Explore Our Services <ArrowUpRight/></Link></div><div className="hero-proof"><span className="proof"><Check/> Practical solutions</span><span className="proof"><Check/> Integrity & confidentiality</span><span className="proof"><Check/> Measurable impact</span></div></div><div className="hero-visual"><div className="compass-card"><span className="eyebrow" style={{color:'#f4ca54'}}>ANCHOR / CONSULTING</span><div className="compass-ring"><div className="compass-needle"/></div><h2>Direction with discipline.</h2><p>Insight-driven strategies that turn business challenges into practical action.</p></div><div className="floating"><div className="floating-number">09</div><div><strong>Business services</strong><span>Across the business lifecycle</span></div></div></div></div></section>
<div className="trust-strip"><div className="container trust-grid"><div className="trust-item"><span className="trust-icon"><Compass/></span>Insight-driven strategies</div><div className="trust-item"><span className="trust-icon"><Shield/></span>Integrity & confidentiality</div><div className="trust-item"><span className="trust-icon"><Chart/></span>Measurable impact</div></div></div>
<section className="section"><div className="container"><SectionTitle eyebrow="Our services" title="Practical expertise across the business lifecycle" text="From setting up a business to strengthening controls and compliance, we help you solve operational problems with clear, usable solutions."/><div className="services-grid">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div><div className="center-button"><Link className="button button-primary" href="/services">View all services <ArrowRight/></Link></div></div></section>
<section className="section soft"><div className="container split"><div className="anchor-panel"><div className="panel-note">Anchored in insights.<br/><strong>Driven by impact.</strong></div><div className="anchor-word">NAVI<span>G</span>ATE.<br/>ALIGN.<br/>GROW.</div></div><div><SectionTitle eyebrow="The Anchor approach" title="Advice should lead to action." text="Your business does not need more complexity. It needs the right questions, clear priorities and processes that people can actually follow."/><div className="feature-list"><div className="feature"><span className="feature-icon"><Spark/></span><div><h3>Practical by design</h3><p>Recommendations are shaped around your operating environment, resources and goals.</p></div></div><div className="feature"><span className="feature-icon"><Shield/></span><div><h3>Built around trust</h3><p>Business information, financial records and operational discussions are handled with discretion.</p></div></div><div className="feature"><span className="feature-icon"><Chart/></span><div><h3>Focused on improvement</h3><p>We translate observations into priorities, actions and better ways of working.</p></div></div></div><div className="check-grid"><div className="check-item"><Check/>Clear communication</div><div className="check-item"><Check/>Structured processes</div><div className="check-item"><Check/>Risk awareness</div><div className="check-item"><Check/>Sustainable growth</div></div></div></div></section>
<section className="section navy"><div className="container"><SectionTitle eyebrow="Who we support" title="Consulting shaped around real business needs" text="Anchor can work with owner-managed businesses, entrepreneurs, professional service firms and individuals who need practical support."/><div className="industry-grid">{industries.map(i=><div className="industry-card" key={i.title}><h3>{i.title}</h3><p>{i.text}</p></div>)}</div></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="Insights" title="Useful thinking for business owners" text="Practical ideas on processes, cash flow, controls, records and business management."/><div className="article-grid">{insights.slice(0,3).map(a=><article className="article-card" key={a.slug}><span className="article-meta">{a.category}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link className="text-link" href={`/insights/${a.slug}`}>Read insight <ArrowUpRight/></Link></article>)}</div><div className="center-button"><Link className="button button-secondary" href="/insights">Browse all insights <ArrowRight/></Link></div></div></section>
<section className="cta"><div className="container cta-inner"><div><span className="eyebrow" style={{color:'#f4ca54'}}>Let’s build a stronger future together</span><h2>Have a business challenge to work through?</h2><p>Tell us where you are today and what you want to improve. We’ll help you identify a practical next step.</p></div><Link className="button button-primary" href="/contact">Start a Conversation <ArrowRight/></Link></div></section>
</main>}
