export const site = {
  name: 'Anchor Business Insights Consulting',
  shortName: 'Anchor Business Insights',
  tagline: 'Anchored in Insights and Driven by Impact',
  description:
    'Practical business consulting in Eldoret, Kenya, supporting business start-ups, advisory, process improvement, credit management, bookkeeping, tax filing, compliance and internal controls.',
  url: process.env.NEXT_PUBLIC_SITE_URL || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000'),
  phone: ['0723 470 776', '0733 439 535'],
  whatsapp: '0723 470 776',
  whatsappUrl: 'https://wa.me/254723470776',
  email: 'anchor-insights@outlook.com',
  address: '1st Floor, Tilil House, Kenyatta Street, Eldoret, Kenya',
  city: 'Eldoret',
  region: 'Uasin Gishu County',
  country: 'Kenya',
  hours: 'Monday–Friday, 8:00 AM–5:00 PM',
};

export const services = [
  { slug: 'business-start-up-management', number: '01', title: 'Business Start-up Management', short: 'Move from idea to launch with a clear, practical foundation.', description: 'Practical support for planning, structuring and organizing a new business before and during launch.', bullets: ['Business planning', 'Start-up structure and setup', 'Operational planning', 'Launch readiness'] },
  { slug: 'credit-management-debt-collection', number: '02', title: 'Credit Management & Debt Collection', short: 'Improve receivables discipline and protect business cash flow.', description: 'Support for credit-control processes, receivables follow-up and structured debt-recovery activities.', bullets: ['Receivables review', 'Credit-control processes', 'Collections follow-up', 'Cash-flow discipline'] },
  { slug: 'business-advisory', number: '03', title: 'Business Advisory', short: 'Turn business challenges into clear priorities and practical action.', description: 'Advisory support for owners and managers who need clearer decisions, performance priorities and risk awareness.', bullets: ['Strategic advisory', 'Performance review', 'Risk review', 'Decision support'] },
  { slug: 'business-process-analysis-alignment', number: '04', title: 'Business Process Analysis & Alignment', short: 'Streamline workflows and align processes for better execution.', description: 'We examine how work moves through the business, identify bottlenecks and help clarify responsibilities and controls.', bullets: ['Process mapping', 'Workflow review', 'Bottleneck identification', 'Process alignment'] },
  { slug: 'bookkeeping-accounting', number: '05', title: 'Bookkeeping & Accounting', short: 'Organized records for better decisions and financial discipline.', description: 'Practical bookkeeping and accounting support for businesses that need reliable records and clearer financial information.', bullets: ['Bookkeeping support', 'Financial records', 'Management information', 'KRA compliance support'] },
  { slug: 'tax-filing', number: '06', title: 'Tax Filing', short: 'Timely and organized support for VAT and statutory filing processes.', description: 'Support for organizing tax records, filing calendars and applicable VAT or statutory filing workflows. Always confirm current obligations with KRA or your tax adviser.', bullets: ['VAT filing support', 'Statutory filing support', 'Tax records organization', 'Filing calendar setup'] },
  { slug: 'career-development-alignment', number: '07', title: 'Career Development & Alignment', short: 'Build skills and align career direction with your goals.', description: 'Practical career-development conversations, skills planning and goal alignment for individuals.', bullets: ['Career planning', 'Skills mapping', 'Goal alignment', 'Professional development'] },
  { slug: 'company-compliance-audit', number: '08', title: 'Company Compliance Audit', short: 'Review compliance requirements and organize a practical action plan.', description: 'A structured review of applicable company, regulatory and statutory requirements, with gaps and actions documented.', bullets: ['Compliance review', 'Gap identification', 'Documentation review', 'Corrective-action planning'] },
  { slug: 'internal-control-audit-blind-spot-analysis', number: '09', title: 'Internal Control Audit & Blind Spot Analysis', short: 'Strengthen controls and identify operational blind spots.', description: 'Review key processes and controls to surface weaknesses, control gaps and operational risks before they become costly problems.', bullets: ['Control review', 'Risk and gap analysis', 'Fraud-risk indicators', 'Improvement recommendations'] },
];

export const industries = [
  { title: 'SMEs & Owner-Managed Businesses', text: 'Practical structure, process and financial discipline for growing businesses.' },
  { title: 'Start-ups & Entrepreneurs', text: 'From business idea to organized launch, with clear priorities and operating basics.' },
  { title: 'Professional Services', text: 'Process, records, controls and compliance support for service-based firms.' },
  { title: 'Retail & Trading', text: 'Credit control, cash-flow discipline, process alignment and internal controls.' },
  { title: 'Community & Growing Organizations', text: 'Structured processes, documentation and accountability for sustainable operations.' },
  { title: 'Individuals & Professionals', text: 'Career planning, skills alignment and professional development support.' },
];

export const insights = [
  { slug: 'why-small-businesses-need-strong-processes', title: 'Why Strong Business Processes Matter as a Company Grows', excerpt: 'How documented and aligned processes can reduce confusion and support consistent execution.', date: '2026-10-01', category: 'Business Management', body: ['Growth often exposes weaknesses that were easy to manage when a business was small. A process that worked informally between two people may become unreliable when responsibilities are shared across a larger team.', 'Business process analysis helps owners understand how work actually moves from one step to another. Mapping the current process can reveal duplicated work, unclear approvals, missing records and bottlenecks.', 'The practical goal is not to create paperwork for its own sake. It is to make important work repeatable, visible and easier to manage. A useful process should identify who does what, when it happens, what information is required and what control or approval is needed.', 'For a growing business, process discipline can support better customer service, accountability and management decisions. Start with the activities that have the greatest effect on customers, cash flow, compliance or operational risk.'] },
  { slug: 'cash-flow-and-credit-management', title: 'Cash Flow Starts With Disciplined Credit Management', excerpt: 'Why credit terms, invoicing and receivables follow-up matter to everyday cash flow.', date: '2026-10-01', category: 'Credit Management', body: ['A sale does not automatically create cash. When customers buy on credit, the business has to manage the period between delivering the product or service and receiving payment.', 'A practical credit-management process begins with clear customer information, agreed terms, accurate invoices and a way to monitor outstanding balances. Follow-up should be consistent and documented rather than dependent on memory.', 'Businesses can also benefit from separating routine reminders from more serious collection cases. That creates a clearer escalation path and helps management see which receivables need attention.', 'Credit management should be aligned with the business model and applicable law. The aim is to improve visibility and cash-flow discipline while maintaining appropriate customer relationships.'] },
  { slug: 'internal-controls-for-growing-businesses', title: 'Internal Controls Every Growing Business Should Review', excerpt: 'A practical way to think about approvals, access, records and accountability.', date: '2026-10-01', category: 'Risk & Controls', body: ['Internal controls are the practical checks that help a business protect resources, keep reliable records and reduce avoidable errors. They should fit the size and complexity of the business.', 'Common areas to review include cash handling, payment approvals, access to accounting systems, inventory records, customer credits, reconciliations and document retention.', 'One useful principle is separation of duties. Where practical, the person initiating a transaction should not have unrestricted control over approval, payment and reconciliation. Smaller businesses may need compensating controls where full separation is not practical.', 'A control review should result in clear actions. Identify the risk, describe the current control, note the gap and assign a responsible person and target date for improvement.'] },
  { slug: 'business-start-up-checklist-kenya', title: 'A Practical Business Start-up Checklist for Kenya', excerpt: 'Questions to work through before turning a business idea into daily operations.', date: '2026-10-01', category: 'Start-up Management', body: ['Starting a business involves more than choosing a name and opening a bank account. A useful start-up plan connects the customer, offer, operating model, finances and compliance requirements.', 'Before launch, define what you will sell, who you will serve, how customers will reach you, how you will deliver the service or product and how money will move through the business.', 'Also identify the registrations, licences, tax and sector requirements that apply to your specific business. Requirements can change, so verify current information with the relevant Kenyan authorities or a qualified adviser.', 'Finally, document the first operating routines: sales, invoicing, cash handling, purchasing, record keeping and customer follow-up. Good routines make it easier to manage the business as activity increases.'] },
  { slug: 'when-to-review-your-business-processes', title: 'When Should a Business Review Its Processes?', excerpt: 'Five practical triggers that suggest it may be time to step back and examine how work is being done.', date: '2026-10-01', category: 'Process Improvement', body: ['Process reviews do not have to wait for a major failure. A business can review its processes when growth, staff changes, customer complaints, repeated errors or new systems change the way work is performed.', 'Repeated delays are a common signal. If customers, suppliers or staff regularly wait for the same approval or information, the underlying workflow may need attention.', 'Another trigger is dependency on one person. When a critical process exists mainly in one employee’s knowledge, documenting and reviewing it can improve continuity.', 'The most useful review is focused. Select one important workflow, document the current state, identify risks and bottlenecks, then agree on a small set of improvements that can actually be implemented.'] },
  { slug: 'keeping-business-records-organized', title: 'Why Organized Business Records Matter', excerpt: 'Reliable records help owners understand performance, support compliance and make decisions with better information.', date: '2026-10-01', category: 'Bookkeeping & Accounting', body: ['Business records are not only for filing requirements. They provide evidence of what happened and help owners understand sales, expenses, receivables, cash movements and other important activities.', 'A practical records system should make it easy to locate source documents and connect them to the relevant accounting entries or business decisions.', 'The exact records and retention periods required depend on the business and applicable law. Businesses should verify current requirements with KRA and other relevant authorities.', 'Regular reconciliation and review can also help identify missing information earlier. Good record keeping is therefore both a compliance activity and a management tool.'] },
];

export type Service = (typeof services)[number];
